//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngenieriaGD.IGDDemo.Library.DAL.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IGDDemoEntities : DbContext
    {
        public IGDDemoEntities()
            : base("name=IGDDemoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IGD_Clients> IGD_Clients { get; set; }
        public virtual DbSet<IGD_Deliveries> IGD_Deliveries { get; set; }
    }
}
