
-- --------------------------------------------------
-- Información inicial de tablas.
-- --------------------------------------------------
-- Date Created: 12/14/2017 19:23:33
-- Generated by: Gabriel Eduardo Duarte Vega
-- --------------------------------------------------

SET QUOTED_IDENTIFIER OFF;
GO
USE [IGDDemo];
GO
IF SCHEMA_ID(N'dbo') IS NULL EXECUTE(N'CREATE SCHEMA [dbo]');
GO

-- --------------------------------------------------
-- Información Tipo de Documentos.
-- --------------------------------------------------
SET IDENTITY_INSERT [dbo].[DocumentTypes] ON
INSERT [dbo].[DocumentTypes] ([Id], [Title], [Code]) VALUES (1, N'Cédula de Ciudadanía', N'CC')
INSERT [dbo].[DocumentTypes] ([Id], [Title], [Code]) VALUES (20, N'Cédula de Extranjería', N'CE')
INSERT [dbo].[DocumentTypes] ([Id], [Title], [Code]) VALUES (22, N'Pasaporte', N'PP')
SET IDENTITY_INSERT [dbo].[DocumentTypes] OFF
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- --------------------------------------------------
-- Información Compañías.
-- --------------------------------------------------
SET IDENTITY_INSERT [dbo].[Companies] ON
INSERT [dbo].[Companies] ([Id], [NIT], [Title]) VALUES (1, 800402578, N'Ingeniería GD®')
SET IDENTITY_INSERT [dbo].[Companies] OFF
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- --------------------------------------------------
-- Información Personas
-- --------------------------------------------------

-- Creating table 'Deliveries'
SET IDENTITY_INSERT [dbo].[People] ON
INSERT [dbo].[People] ([Id], [DocumentNumber], [DocumentTypeId], [FirstName], [SecondName]) VALUES (1, N'80040257', 1, 'Gabriel', 'Duarte')
SET IDENTITY_INSERT [dbo].[People] OFF
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- --------------------------------------------------
-- Información Clientes
-- --------------------------------------------------
SET IDENTITY_INSERT [dbo].[Clients] ON
INSERT [dbo].[Clients] ([Id], [Phone], [LastReading], [Readed], [PersonId], [Anniversary], [Email], [Address]) VALUES (1, N'3115629864', 11, 0, 1, '2005-06-29Z', N'geduartev@gmail.com', N'Bogotá DC')
SET IDENTITY_INSERT [dbo].[Clients] OFF
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

-- --------------------------------------------------
-- Script has ended
-- --------------------------------------------------